version: '3.8'

services:
  leviton-agent-backend:
    build: .
    container_name: leviton-agent-backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - API_KEY=${API_KEY}
      - MAX_ITERATIONS=${MAX_ITERATIONS}
      - MCP_ACCESS_TOKEN=${MCP_ACCESS_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PROJECT_NAME=${PROJECT_NAME}
      - PHOENIX_ENDPOINT=${PHOENIX_ENDPOINT}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
      - RAINFOREST_API_KEY=${RAINFOREST_API_KEY}
    volumes:
      - agent-data:/app/data
      - agent-logs:/app/logs
    networks:
      - leviton-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 添加 Cloudflare Tunnel 服务
#注册了一个： api-leviton-agent.zhangzic.workers.dev

   
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped
    networks:
      - leviton-network  # 回到容器网络
    depends_on:
      - leviton-agent-backend


volumes:
  agent-data:
    driver: local
  agent-logs:
    driver: local

networks:
  leviton-network:
    driver: bridge 