version: '3.8'

services:
  leviton-agent-backend:
    build: .
    container_name: leviton-agent-backend
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - API_KEY=${API_KEY}
      - MAX_ITERATIONS=${MAX_ITERATIONS}
      - MCP_ACCESS_TOKEN=${MCP_ACCESS_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PROJECT_NAME=${PROJECT_NAME}
      - PHOENIX_ENDPOINT=${PHOENIX_ENDPOINT}
      - APIFY_API_TOKEN=${APIFY_API_TOKEN}
      - RAINFOREST_API_KEY=${RAINFOREST_API_KEY}
    volumes:
      - agent-data:/app/data
      - agent-logs:/app/logs
    networks:
      - leviton-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:alpine
    container_name: caddy-proxy
    ports:
      - "80:80"
      - "443:443"
    command: caddy reverse-proxy --from 3po-agent.duckdns.org --to leviton-agent-backend:8000
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - leviton-network
    depends_on:
      - leviton-agent-backend
    restart: unless-stopped

volumes:
  agent-data:
    driver: local
  agent-logs:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  leviton-network:
    driver: bridge