from __future__ import annotations

import logging
from typing import List, Optional
from dataclasses import asdict

from supabase import Client  # type: ignore

from review_analysis.models import Aspect

logger = logging.getLogger(__name__)

_TABLE = "review_analysis_aspects"  # Postgres / Supabase table name


class AspectRepository:  # noqa: WPS110 – repo naming
    """Data-access helpers for the *aspect* dimension table."""

    def __init__(self, client: Client):
        self._client = client

    # ------------------------------------------------------------------
    # Inserts
    # ------------------------------------------------------------------

    async def batch_insert(self, aspects: List[Aspect]) -> List[int]:  # noqa: D401 – async
        """Insert *aspects* and return the generated primary keys.

        Duplicate rows (same product_id, aspect_type, local_id) are ignored –
        the existing PK is returned instead so callers can link occurrences
        without re-querying.
        """
        if not aspects:
            return []

        # Convert to dict but exclude aspect_pk since it's auto-generated
        payload = []
        for aspect in aspects:
            aspect_dict = asdict(aspect)
            # Remove aspect_pk since it should be auto-generated by the database
            aspect_dict.pop('aspect_pk', None)
            payload.append(aspect_dict)
        
        try:
            result = (
                self._client.table(_TABLE)
                .upsert(payload, on_conflict="project_id,product_id,aspect_type,local_id")
                .execute()
            )
            return [row["aspect_pk"] for row in result.data] if result.data else []
        except Exception as exc:  # pylint: disable=broad-except
            logger.exception("Failed to insert aspects: %s", exc)
            return []

    # ------------------------------------------------------------------
    # Updates
    # ------------------------------------------------------------------

    async def update_category(self, aspect_pk: int, category_pk: int) -> bool:  # noqa: D401
        """Set *category_pk* for the given aspect."""
        try:
            res = (
                self._client.table(_TABLE)
                .update({"category_pk": category_pk})
                .eq("aspect_pk", aspect_pk)
                .execute()
            )
            return bool(res.data)
        except Exception as exc:
            logger.exception("Failed to update aspect category: %s", exc)
            return False

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    async def get_by_pk(self, aspect_pk: int) -> Optional[dict]:
        try:
            res = self._client.table(_TABLE).select("*").eq("aspect_pk", aspect_pk).single().execute()
            return res.data  # type: ignore[return-value]
        except Exception as exc:
            logger.exception("Failed to lookup aspect: %s", exc)
            return None

    async def get_for_product(self, product_id: str) -> List[dict]:  # noqa: D401
        try:
            res = self._client.table(_TABLE).select("*").eq("product_id", product_id).execute()
            return res.data or []  # type: ignore[return-value]
        except Exception as exc:
            logger.exception("Failed to list aspects: %s", exc)
            return [] 